module.exports = {
    main_Screen:{
        marginTop:'20%',
        diplay:'flex',
        flexDirection:'column',
        backgroundColor:'black',
        alignItems:'center',
        width:'100%',
        height:'100%'
    },
    main_screen_display:{
        width:'100%',
        backgroundColor:'black',
        display:'flex',
        marginBottom:10,
        padding:10,
    },
    main_screen_display_text:{
        fontSize:40,
        textAlign:'right',
        color:'#04E1FF'
    },
    main_screen_keypad:{
        width:'100%',
        height:'65%',
        display:'flex',
    },
    main_screen_keypad_row:{
        display:'flex',
        flexDirection:'row',
        width:'100%',
        justifyContent:'space-between',
        alignItems:'center',
        padding:6,
    },
    btn_outer:{
        width:70,
        height:70,
        backgroundColor:'#222222',
        elevation:10,
        overflow:'hidden',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:50,
    },
    bg_button:{
        color:'#04E1FF',
        fontSize:30,
    },
    bg1_button:{
        color:'#F22323',
        fontSize:30
    },
    bg2_button:{
        color:'#04E1FF',
        fontSize:25,
        fontWeight:'bold'
    },
    btn1_outer:{
        width:70,
        height:70,
        backgroundColor:'#222222',
        elevation:10,
        overflow:'hidden',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:50,
    },
    btn2_outer:{
        width:70,
        height:70,
        backgroundColor:'#222222',
        elevation:10,
        overflow:'hidden',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:50,
    }

}